"""rename phone to contact_number

Revision ID: 236e6305b9e4
Revises: d2106fd9e41b
Create Date: 2026-09-10 16:23:54.446400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236e6305b9e4'
down_revision: Union[str, Sequence[str], None] = 'd2106fd9e41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'phone', new_column_name='contact_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'contact_number', new_column_name='phone')
    # ### end Alembic commands ###
