# Task 7: Autogenerate blind spots + rollback safety

# Part 1 — expose the rename problem
# - In models.py, rename Patient.phone to Patient.contact_number
# - PREDICT (before running): will autogenerate produce an alter_column/rename,
#   or will it produce drop_column + add_column? Justify in one sentence.
# - Run: alembic revision --autogenerate -m "rename phone to contact_number"
# - Paste the FULL generated migration content
# - Confirm whether your prediction was right


# PREDICTION: The autogenerate feature will produce a drop_column + add_column operation instead of an alter_column/rename because it detects the removal of the 'phone' column and the addition of the 'contact_number' column as two separate changes, rather than recognizing it as a rename operation.

# The generated migration content is:
# (.venv) PS D:\python-practice\sqlalchemy-practice> alembic revision --autogenerate -m "rename phone to contact_number"
# INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
# INFO  [alembic.runtime.migration] Will assume transactional DDL.
# INFO  [alembic.runtime.plugins] setting up autogenerate plugin alembic.autogenerate.schemas
# INFO  [alembic.runtime.plugins] setting up autogenerate plugin alembic.autogenerate.tables
# INFO  [alembic.runtime.plugins] setting up autogenerate plugin alembic.autogenerate.types
# INFO  [alembic.runtime.plugins] setting up autogenerate plugin alembic.autogenerate.constraints
# INFO  [alembic.runtime.plugins] setting up autogenerate plugin alembic.autogenerate.defaults
# INFO  [alembic.runtime.plugins] setting up autogenerate plugin alembic.autogenerate.comments
# INFO  [alembic.ddl.postgresql] Detected sequence named 'appointments_id_seq' as owned by integer column 'appointments(id)', assuming SERIAL andomitting
# INFO  [alembic.ddl.postgresql] Detected sequence named 'patients_id_seq' as owned by integer column 'patients(id)', assuming SERIAL and omittingINFO  [alembic.autogenerate.compare.tables] Detected added column 'patients.contact_number'
# INFO  [alembic.autogenerate.compare.tables] Detected removed column 'patients.phone'
# Generating D:\python-practice\sqlalchemy-practice\alembic\versions\236e6305b9e4_rename_phone_to_contact_number.py ...  done
# (.venv) PS D:\python-practice\sqlalchemy-practice>

# Part 2 — fix it manually
# - If the generated migration used drop_column/add_column, manually rewrite
#   upgrade() and downgrade() to use op.alter_column(..., new_column_name=...) instead
# - PREDICT: if you had applied the AUTO version instead of your manual fix,
#   and a row already had a phone number saved, what would happen to that data?


# The data would be lost because the auto-generated migration would drop the old column and create a new one, resulting in the loss of any existing data in the 'phone' column.

# After the manual fix:
# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('patients', 'phone', new_column_name='contact_number')
#     # ### end Alembic commands ###
# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('patients', 'contact_number', new_column_name='phone')
#     # ### end Alembic commands ###

# Task 8 — test rollback for real, don't just trust the code
# - Run: alembic current          -> record the actual output
# - Run: alembic upgrade head     -> apply your manual rename migration
# - Manually insert one row with a value in contact_number (paste the INSERT + confirmation)
# - Run: alembic downgrade -1     -> paste FULL output
# - Query the table again: did contact_number/phone column survive, and did the
#   VALUE you inserted survive, or is it gone?
# - PREDICT this outcome BEFORE running downgrade, then compare to what you actually got

# (.venv) PS D:\python-practice\sqlalchemy-practice> alembic current
# INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
# INFO  [alembic.runtime.migration] Will assume transactional DDL.
# d2106fd9e41b
# (.venv) PS D:\python-practice\sqlalchemy-practice> alembic upgrade head
# INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
# INFO  [alembic.runtime.migration] Will assume transactional DDL.
# INFO  [alembic.runtime.migration] Running upgrade d2106fd9e41b -> 236e6305b9e4, rename phone to contact_number

# The SQL command to insert a row with a value in contact_number:
# INSERT INTO patients (name, age, contact_number) VALUES ('John Doe', 30, '123-456-7890');

# (.venv) PS D:\python-practice\sqlalchemy-practice> alembic downgrade -1
# INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
# INFO  [alembic.runtime.migration] Will assume transactional DDL.
# INFO  [alembic.runtime.migration] Running downgrade 236e6305b9e4 -> d2106fd9e41b, rename phone to contact_number
# The value in the contact_number column should survive the downgrade because the manual migration uses alter_column to rename the column instead of dropping and creating a new one. Therefore, the data should remain intact after the downgrade.

# It actually survived, confirming that the manual migration preserved the data during the downgrade process.
# SELECT * FROM patients;
# 2	John Doe	30	123-456-7890